
networks:
  my_network:
    driver: bridge

services:
  service1:
    build:
      context: ./api1
      dockerfile: Dockerfile
    networks:
      - my_network
    # ports:
    #   - "3001:3001"

  service2:
    build:
      context: ./api2
      dockerfile: Dockerfile
    networks:
      - my_network
    # ports:
    #   - "3002:3002"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my_network
    depends_on:
      - service1
      - service2
