version: '3.8'

services:

  server-1:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  server-2:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "3002:3002"
    environment:
      - PORT=3002

  server-3:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "3003:3003"
    environment:
      - PORT=3003

  server-4:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "3004:3004"
    environment:
      - PORT=3004

  server-5:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "3005:3005"
    environment:
      - PORT=3005

  server-6:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "3006:3006"
    environment:
      - PORT=3006

  server-7:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "3007:3007"
    environment:
      - PORT=3007

  server-8:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "3008:3008"
    environment:
      - PORT=3008

  server-9:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "3009:3009"
    environment:
      - PORT=3009

  server-10:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - my_network
    ports:
      - "3010:3010"
    environment:
      - PORT=3010


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my_network
    depends_on:

      - server-1

      - server-2

      - server-3

      - server-4

      - server-5

      - server-6

      - server-7

      - server-8

      - server-9

      - server-10


networks:
  my_network:
    driver: bridge